services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      # Optioneel: dashboard via / (8080)
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-net

  mywebsite:
    image: httpd:2.4
    container_name: mywebsite
    volumes:
      # Mount jouw lokale HTML in de Apache webroot
      - ./mywebsite:/usr/local/apache2/htdocs/
    labels:
      - "traefik.enable=true"
      # Router: stuur host mywebsite.localhost naar deze container
      - "traefik.http.routers.mywebsite.rule=Host(`mywebsite.localhost`)"
      - "traefik.http.routers.mywebsite.entrypoints=web"
      # Service: welke poort luistert Apache in de container? (80)
      - "traefik.http.services.mywebsite.loadbalancer.server.port=80"
    networks:
      - traefik-net

networks:
  traefik-net:
    name: traefik-net
